# Generated by Django 4.1.7 on 2023-06-04 09:53

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('recipe_required', models.BooleanField()),
                ('manufacturer_address', models.CharField(max_length=255)),
                ('indications_for_use', models.TextField()),
                ('method_of_application', models.TextField()),
                ('side_effects', models.TextField()),
                ('interaction_with_other_medicines', models.TextField()),
                ('shelf_life', models.CharField(max_length=50)),
                ('date_of_manufacture', models.DateField()),
                ('composition', models.TextField()),
                ('amount_in_stock', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('contraindications', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_address', models.CharField(default=None, max_length=255, null=True)),
                ('date_created', models.DateTimeField(default=datetime.datetime.now)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('is_paid', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_code', models.CharField(max_length=1, unique=True)),
                ('status_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FIO', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('userprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pharmacy_calc.userprofile')),
            ],
            bases=('pharmacy_calc.userprofile',),
        ),
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('userprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pharmacy_calc.userprofile')),
                ('is_free', models.BooleanField(default=True)),
            ],
            bases=('pharmacy_calc.userprofile',),
        ),
        migrations.CreateModel(
            name='Pharmacist',
            fields=[
                ('userprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pharmacy_calc.userprofile')),
                ('is_free', models.BooleanField(default=True)),
            ],
            bases=('pharmacy_calc.userprofile',),
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosage', models.CharField(max_length=50)),
                ('duration', models.PositiveIntegerField()),
                ('code', models.CharField(max_length=50)),
                ('expiration_date', models.DateField()),
                ('medicament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy_calc.medicament')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy_calc.client')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_approve', models.BooleanField(blank=True, null=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('medicament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy_calc.medicament')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='pharmacy_calc.order')),
                ('recipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pharmacy_calc.recipe')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='pharmacy_calc.orderstatus'),
        ),
        migrations.AddField(
            model_name='order',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy_calc.client'),
        ),
        migrations.AddField(
            model_name='order',
            name='courier',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='pharmacy_calc.courier'),
        ),
        migrations.AddField(
            model_name='order',
            name='pharmacist',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='pharmacy_calc.pharmacist'),
        ),
    ]
